### ISSUE TITLE
Warning on Elixir 1.16

### ISSUE THREAD

**Issue by thbar** [PSPDFKit-labs/bypass#142]
```
    warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
    │
  6 │   if Application.get_env(:bypass, :enable_debug_log, false) do
    │                  ~
    │
    └─ lib/bypass/utils.ex:6:18: Bypass.Utils (module)
```

**Comment by wkirschbaum** [comment]
This should be fixed by: https://github.com/PSPDFKit-labs/bypass/pull/139 and the commit in the comments.

**Comment by bszaf** [comment]
Resoled via #139

**Comment by thbar** [comment]
Thank you!!!

**Comment by jaimeiniesta** [comment]
Hi, this warning is still present for Elixir 1.19 (but it's gone when you install the library from github); I guess the fix hasn't been released yet.
